# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-22 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=20)),
                ('Color', models.CharField(max_length=20)),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('Size', models.CharField(max_length=15)),
                ('Quantity', models.IntegerField()),
                ('Gender', models.CharField(max_length=6)),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
    ]
