# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-29 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingInventoryProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='Size',
            field=models.CharField(max_length=20),
        ),
    ]
