# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-14 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClothingInventoryProject', '0002_auto_20181029_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='Image',
            field=models.ImageField(default='Null', upload_to=''),
        ),
    ]
